import { test } from 'node:test';
import assert from 'node:assert/strict';
import { pbkdf2Sync } from 'node:crypto';
import sharp from 'sharp';
import { createHandler } from '../lib/backend.mjs';
const salt='ab'.repeat(32), password='TestPassword!';
const account={username:'TestAdmin',salt,hash:pbkdf2Sync(password,Buffer.from(salt,'hex'),600000,32,'sha256').toString('hex')};
test('authentication, persistent edits, image validation and deletion',async()=>{
 const records=new Map();
 const store={get:async k=>records.get(k)??null,setJSON:async(k,v)=>records.set(k,structuredClone(v)),set:async(k,v)=>records.set(k,v),delete:async k=>records.delete(k),async *list({prefix}){yield {blobs:[...records.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}};
 let handler=createHandler({store,account}), cookie='';
 const request=(path,data,headers={})=>handler(new Request('https://example.com'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json',cookie,...headers},body:data===undefined?undefined:JSON.stringify(data)}));
 assert.equal((await request('/api/gallery/events',{title:'Test',date:'2026-09-23'})).status,401);
 for(const credentials of [{username:'testadmin',password},{username:'TestAdmin',password:'testpassword!'}, {username:"' OR 1=1 --",password}]) assert.equal((await request('/api/login',credentials)).status,401);
 const login=await request('/api/login',{username:account.username,password});
 assert.equal(login.status,200); assert.match(login.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/); cookie=login.headers.get('set-cookie').split(';')[0];
 assert.equal((await (await request('/api/session')).json()).authenticated,true);
 assert.equal((await request('/api/gallery/events',{title:'bad',date:'2026-02-30'})).status,400);
 assert.equal((await request('/api/event-info',{description:'bad'},{origin:'https://evil.example'})).status,403);
 const image='data:image/png;base64,'+(await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer()).toString('base64');
 assert.equal((await request('/api/event-info',{description:'Saved',image})).status,200);
 handler=createHandler({store,account});
 assert.equal((await (await request('/data/event-info.json')).json()).description,'Saved');
 const created=await (await request('/api/gallery/events',{title:'Test',date:'2026-09-23'})).json(),eventId=created.events[0].id;
 assert.equal((await request('/api/gallery/photos',{eventId,image:'data:image/png;base64,aaaa'})).status,400);
 let gallery=await (await request('/api/gallery/photos',{eventId,image})).json();
 const photo=gallery.events[0].photos[0]; assert.equal((await request(photo.url)).status,200);
 await request('/api/gallery/delete-photo',{eventId,photoId:photo.id}); assert.equal((await request(photo.url)).status,404);
 gallery=await (await request('/api/gallery/photos',{eventId,image})).json();
 await request('/api/gallery/delete-event',{eventId}); assert.deepEqual(await (await request('/data/gallery.json')).json(),{events:[]});
 assert.equal((await request(gallery.events[0].photos[0].url)).status,404);
 assert.equal((await request('/api/gallery/photos',{eventId,image})).status,404);
 const logout=await request('/api/logout?returnTo=/gallery.html',{});assert.equal(logout.headers.get('location'),'/gallery.html');
 assert.equal((await (await request('/api/session')).json()).authenticated,false);
 assert.equal((await request('/api/event-info',{description:'forbidden'})).status,401);
});
